kh:
    parsing_settings:
        date_format: "%Y.%m.%d"
        delimiter: "\t"
        csv_read_type: "dict_reader"
    csv_column_config:
        payee:
            - "típus"
            - "partner elnevezése"
        notes: "közlemény"
        date: "könyvelés dátuma"
        currency: "összeg devizaneme"
        amount: "összeg"
        asset_id: "könyvelési számla"
otp_debit:
    parsing_settings:
        date_format: "%Y%m%d"
        delimiter: ";"
        csv_read_type: "line_reader"
    csv_column_config:
        payee: 8
        notes: 12
        date: 5
        currency: 3
        amount: 2
        asset_id: 0
otp_credit:
    parsing_settings:
        date_format: "%Y%m%d"
        delimiter: ";"
        csv_read_type: "line_reader"
    csv_column_config:
        payee: 10
        notes: 9
        date: 4
        currency: "huf"
        amount: 2
        asset_id: 0
n26:
    parsing_settings:
        delimiter: ","
        date_format: "%Y-%m-%d"
        csv_read_type: "dict_reader"
    csv_column_config:
        payee: "Payee"
        notes: "Payment reference"
        date: "Date"
        amount: "Amount (%s)"
        asset_id: "currency"
revolut:
    parsing_settings:
        date_format: "%Y-%m-%d %H:%M:%S"
        delimiter: ","
        csv_read_type: "dict_reader"
    csv_column_config:
        payee: "Description"
        notes: "Type"
        date: "Completed Date"
        amount: "Amount"
        currency: "Currency"
        asset_id: "Currency"