kh:
    parsing_settings:
        date_format: "%Y.%m.%d"
        delimiter: "\t"
        csv_read_type: "dict_reader"
    csv_column_config:
        payee:
            - "típus"
            - "partner elnevezése"
        notes: "közlemény"
        date: "könyvelés dátuma"
        currency: "összeg devizaneme"
        amount: "összeg"
        asset_id: "könyvelési számla"
otp:
    parsing_settings:
        date_format: "%Y-%m-%d"
        delimiter: ";"
        csv_read_type: "dict_reader"
    csv_column_config:
        payee: "Partner neve"
        notes: "Közlemény"
        date: "Könyvelés dátuma"
        currency: "Pénznem"
        amount: "Összeg"
        asset_id: "Számla szám"
n26:
    parsing_settings:
        delimiter: ","
        date_format: "%Y-%m-%d"
        csv_read_type: "dict_reader"
    csv_column_config:
        payee: "Payee"
        notes: "Payment reference"
        date: "Date"
        amount: "Amount (%s)"
        asset_id: "currency"
revolut:
    parsing_settings:
        date_format: "%Y-%m-%d %H:%M:%S"
        delimiter: ","
        csv_read_type: "dict_reader"
    csv_column_config:
        payee: "Description"
        notes: "Type"
        date: "Completed Date"
        amount: "Amount"
        currency: "Currency"
        asset_id: "Currency"