name: Banker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Run test
          uses: dschep/install-pipenv-action@v1
          run: pipenv install -d
          run: echo "::set-env name=PYTHONPATH::$GITHUB_WORKSPACE/lib"1
          run: echo 'PYTHONPATH is' $PYTHONPATH
          run: pipenv run test
          env:
            ENV: test
