name: Banker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install pipenv
          run: pip install pipenv
        - name: Depedency install
          run: pipenv install -d
        - name: Set PYTHONPATH
          run: echo "::set-env name=PYTHONPATH::$GITHUB_WORKSPACE/lib"
        - name: Get PYTHONPATH
          run: echo 'PYTHONPATH is' $PYTHONPATH
        - name: Test run
          run: pipenv run test
          env:
            ENV: test
